site_name: Diário da Saúde - Documentação
theme:
  name: material
  language: pt
pages:
  - Home: index.md
  - Planejamento: planejamento.md
  - Pré-rastreabilidade:
    - Argumentação: argumentacao.md
    - RichPicture: rich_picture.md
