site_name: Diário da Saúde
theme:
  name: windmill
  language: pt
nav:
  - Home: index.md
  - Reuniões:
    - Ata 1 (31/08/2020): ata_1.md
    - Ata 2 (02/09/2020): ata_2.md 
    - Ata 3 (04/09/2020): ata_3.md
    - Ata 4 (06/09/2020): ata_4.md
    - Ata 5 (09/09/2020): ata_5.md
  - Desenho de Software (Base):
    - 5W2H: 5w2h.md
    - RichPictures: rich_picture.md
    - Argumentação: argumentacao.md
    - Questionário: questionario.md
    - Mapa Mental: mapa_mental.md
    - Diagrama Causa-Efeito: diagrama_de_causa_e_efeito.md
    - Plano de Análise:
      - Risco: plano_risco.md
      - Esforço e Tempo: plano_esforco_tempo.md
      - Custo: plano_custo.md
    - Priorização: priorizacao.md
    - Brainstorm: brainstorm.md
    - Storyboard: story_board.md
    - Design Sprint: design_sprint.md
    - Identidade Visual: identidade_visual.md
    - Protótio: prototipo.md
