site_name: Diário da Saúde
theme:
  name: windmill
  language: pt
nav:
  - Home: index.md
  - Reuniões:
    - Ata 1 (31/08/2020): ata_1.md
    - Ata 2 (02/09/2020): ata_2.md 
    - Ata 3 (04/09/2020): ata_3.md
    - Ata 4 (06/09/2020): ata_4.md
    - Ata 5 (09/09/2020): ata_5.md
    - Ata 6 (10/09/2020): ata_6.md
    - Ata 7 (11/09/2020): ata_7.md
    - Ata 8 (23/09/2020): ata_8.md
    - Ata 9 (25/09/2020): ata_9.md
  - Desenho de Software (Base):
    - Módulo Projeto não Orientado a Abordagens Específicas:
      - 5W2H: 5w2h.md
      - Diagrama Causa-Efeito: diagrama_de_causa_e_efeito.md
      - Plano de Análise:
        - Risco: plano_risco.md
        - Esforço e Tempo: plano_esforco_tempo.md
        - Custo: plano_custo.md
      - Design Sprint:
        - Design Sprint: design_sprint.md
        - Brainstorm: brainstorm.md
        - Mapa Mental: mapa_mental.md
        - RichPictures: rich_picture.md
        - Storyboard: story_board.md
        - Protótipo: prototipo.md
        - Questionário: questionario.md
    - Módulo Processos/Metodologia/Abordagens (Apresentação):
      - Metodologia: metodologia.md
    - Módulo Processos/Metodologia/Abordagens (Modelagem):
      - BPMN: BPMN.md
    - Iniciativas extras:
      - Argumentação: argumentacao.md
      - Introspecção: introspeccao.md
      - Priorização: priorizacao.md
      - Backlog: backlog_produto.md
      - Identidade Visual: identidade_visual.md
  - Desenho de Software (Modelagem):
    - Notação UML - Diagramas Estáticos:
      - Diagrama de Classes: diagrama_de_classes.md
      - Diagrama de Pacotes: diagrama_de_pacotes.md
      - Diagrama de Componentes: diagrama_de_componentes.md
    - Notação UML - Diagramas Dinâmicos:
      - Diagrama de Sequência: diagrama_de_sequencia.md
      - Diagrama de Comunicação: diagrama_de_comunicacao.md
      - Diagrama de Atividades: diagrama_de_atividades.md
      - Diagrama de Estados: diagrama_de_estado.md
    - Iniciativas extras:
      - Backlog: backlog_produto.md

repo_url: https://github.com/UnBArqDsw/2020.1_G5_Diario_da_Saude
extra:
  logo: img/logo_branca.png
extra_css:
  - css/extra.css
