site_name: Diário da Saúde
theme:
  name: windmill
  language: pt
nav:
  - Home: index.md
  - Desenho de Software (Base):
    - 5W2H: 5w2h.md
    - RichPictures: rich_picture.md
    - Mapa Mental: mapa_mental.md
    - Diagrama Causa-Efeito: diagrama_de_causa_e_efeito.md
    - Plano de Análise de Risco: plano_risco.md
    - Plano de Análise de Esforço e Tempo: plano_esforco_tempo.md
    - Plano de Análise de Custo: plano_custo.md
    - Priorização: priorizacao.md
    - Brainstorm: brainstorm.md
    - Storyboard: story_board.md
    - Design Sprint: design_sprint.md
