site_name: Diário da Saúde - Documentação
theme:
  name: minty
  language: pt
pages:
  - Home: index.md
  - Desenho de Software (Base):
    - Brainstorm: brainstorm.md
    - 5W2H: 5w2h.md
    - RichPictures: rich_pictures.md
